[mypy]
python_version = 3.12
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
no_implicit_optional = true
strict_equality = true
show_error_codes = true
pretty = true
namespace_packages = true
explicit_package_bases = true

[mypy-pydantic.*]
ignore_missing_imports = true

[mypy-sentence_transformers.*]
ignore_missing_imports = true

[mypy-ollama.*]
ignore_missing_imports = true
