"""Curve templates and pack/unpack helpers for curve-based IOPs."""

from .packing import (
    CATMULL_ROM,
    COLORZONES_SIZE,
    CUBIC_SPLINE,
    MAX_CURVE_CHANNELS,
    MAX_CURVE_NODES,
    MONOTONE_HERMITE,
    RGBCURVE_SIZE,
    TONECURVE_SIZE,
    ZONES_SMOOTH,
    ZONES_STRONG,
    ColorzonesParams,
    RGBCurveParams,
    TonecurveParams,
    apply_curve_template,
    apply_curve_template_colorzones,
    apply_curve_template_rgbcurve,
    apply_curve_template_tonecurve,
    curve_iop_size,
    pack_colorzones,
    pack_rgbcurve,
    pack_tonecurve,
    unpack_colorzones,
    unpack_rgbcurve,
    unpack_tonecurve,
)
from .templates import (
    REGISTRY,
    CurveTemplate,
    get_template,
    list_templates,
    render_template_summary,
)

__all__ = [
    "REGISTRY",
    "CurveTemplate",
    "get_template",
    "list_templates",
    "render_template_summary",
    "MAX_CURVE_NODES",
    "MAX_CURVE_CHANNELS",
    "CUBIC_SPLINE",
    "CATMULL_ROM",
    "MONOTONE_HERMITE",
    "ZONES_SMOOTH",
    "ZONES_STRONG",
    "ColorzonesParams",
    "RGBCurveParams",
    "TonecurveParams",
    "COLORZONES_SIZE",
    "RGBCURVE_SIZE",
    "TONECURVE_SIZE",
    "apply_curve_template",
    "apply_curve_template_colorzones",
    "apply_curve_template_rgbcurve",
    "apply_curve_template_tonecurve",
    "pack_colorzones",
    "pack_rgbcurve",
    "pack_tonecurve",
    "unpack_colorzones",
    "unpack_rgbcurve",
    "unpack_tonecurve",
    "curve_iop_size",
]
